### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by brurend** [mgambati/fastlane-plugin-discord#1]
Could you show an example of how to use the plugin please?

**Comment by mgambati** [comment]
Sorry for the delay. 

To use the plugin just put `gem 'fastlane-plugin-discord'` on `Pluginfile` and on `Fastfile` after the build put it like the code snippet down. Remember to also create a Webhook URL on Discord.

```rb
  DISCORD_WEBHOOK_URL = 'url here'

  # Notify discord about the new build
  discord(
    url: DISCORD_WEBHOOK_URL ,
    app_name: 'App Name',
    platform: 'ios', // or android
    version: VERSION,
    build_number: BUILD_NUMBER
  )
```

The notification will look like this:

![image](https://user-images.githubusercontent.com/813131/61579404-86077300-aad2-11e9-8258-014e9c3e2add.png)
